# https://www.youtube.com/watch?v=f-7HP9doQOQ   CodeWriter
# docker compose up -d

version: '3'

services:
  php:
    container_name: OfficePHPV01
    build:
      context: dockerFiles
      dockerfile: php.Dockerfile
#   dockerfile: 
    volumes:
      - ./docker/www/public_html:/var/www/public_html
    depends_on:
      - mysql
    networks:
      - AmNet 

  nginx:
    container_name: OfficeNginxV01
    image: nginx:latest
    ports:
      - 8000:80
      - 3000:443
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./web:/var/www/html"

#     - ./docker/nginx/conf.d:/etc/nginx/conf.d'
# - './docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf: ro'
# посмотреть варианты рестарта (unless-stopped - не перегружать без ведома)
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - AmNet
# Не забыть .env файлик  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  
  mysql:
    container_name: OfficeMySQLV01
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

    networks:
      - AmNet

  phpmyadmin:
    image: phpmyadmin
    container_name: OfficePHPMyAdminV01
    restart: always
    ports:
      - 9090:80
    environment:
#PMA_ARBITRARY=1 - указывает на то что возможно подключение к произвольному серверу базы данных 
#(Как привязать к конкретному серверу панель phpmyadmin, можно ознакомиться в этой статье) https://zomro.com/rus/blog/faq/290-kak-ustanovit-mariadb-v-docker

      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - AmNet          
# network    
networks:
  AmNet:
     name: AmNet
     driver: bridge
     
